name: adamharbottle
favicon: null
layout_spectrum: 0.4907338118646294
typography_spectrum: 0.7898920993320644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecfd1'
    - '#0a0809'
    - '#3f2920'
    - '#9c826b'
    - '#74543f'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0
purpose: []
